# Generated by Django 4.0.3 on 2022-06-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='cinema')),
                ('post', models.CharField(max_length=255, unique=True)),
                ('degree', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Доктора',
            },
        ),
    ]
