# Generated by Django 4.0.5 on 2022-06-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medclinic', '0003_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name_plural': 'Записи'},
        ),
    ]
