# Generated by Django 4.0.5 on 2022-06-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medclinic', '0008_rename_name_appointment_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='post',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
